spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
#  redis:
#    host: 47.114.173.248
#    password: osRedis
#    port: 6379
#    database: 9
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: utf-8
    cache: false
mybatis:
  type-aliases-package: com.wjy.test.entity
  mapper-locations: classpath*:mapper/*.xml
  type-handlers-package: com.ph.handler
  configuration:
    map-underscore-to-camel-case: true
  #mybatis打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
    configuration:
       log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ph-core:
  swagger:
    enable: true
  controller-package: com.ph.controller
  redis-key: ph
  submail:
    app-id: xxxxx
    app-key: xxxxx
    code-model: xxxxx
    code-var: code
  simple-auth:
    session:
      name: ph_session_id


privilege:
  check:
    enable: false

oss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAI4GBds5QSiuyNi4u5TmDC
  accessKeySecret: m94K876t49Q4m0mErjdrVktLHCkHT4
  bucketName: kxyjr
  filedir: images